"""
ORACLE Release Readiness Intelligence (Brick 4.0)
Autonomous, evidence-backed, cross-system decision engine for enterprise release readiness.
"""

from backend.release.models import (
    CIBuildStatus,
    CIPipelineRun,
    CodeReviewStatus,
    FindingStatus,
    GovernedActionProposal,
    GovernedActionStatus,
    GovernedActionType,
    PullRequestReview,
    ReleaseAssessment,
    ReleaseCandidate,
    ReleaseDecision,
    ReleaseDecisionOutcome,
    ReleaseRecommendation,
    RiskLevel,
    SecurityCategory,
    SecurityFinding,
    SecuritySeverity,
    WorkItem,
    WorkItemStatus,
)
from backend.release.providers import (
    BaseReleaseDataProvider,
    CICDProvider,
    GitReleaseProvider,
    InMemoryReleaseDataProvider,
    SecurityScanProvider,
    WorkManagementProvider,
)
from backend.release.correlation import CrossSystemCorrelator
from backend.release.investigation import ReleaseReadinessInvestigator
from backend.release.decision import ReleaseDecisionEngine
from backend.release.actions import (
    ActionDispatcher,
    ActionValidationError,
    ActionAuthorizationError,
    GovernedActionExecutor,
    LiveActionDispatcher,
    LiveActionPolicyError,
    SimulatedActionDispatcher,
)
from backend.release.api import ReleaseReadinessAPI
from backend.release.config import (
    JiraFieldMappingConfig,
    OracleReleaseConfig,
    ProviderFactory,
    ProviderMode,
)
from backend.release.connectivity import (
    CircuitBreaker,
    CircuitBreakerOpenError,
    CircuitState,
    CredentialProvider,
    EnterpriseReleaseDataProvider,
    EnvCredentialProvider,
    GLOBAL_REDACTOR,
    GitHubActionsCICDProvider,
    GitHubReleaseProvider,
    InMemoryCredentialVault,
    InvestigationTelemetryLedger,
    JiraWorkManagementProvider,
    ProviderAuthenticationError,
    ProviderNetworkError,
    ProviderOperationTelemetry,
    ProviderOutageError,
    ProviderRateLimitError,
    ProviderTimeoutError,
    ResilientHttpClient,
    SecretRedactor,
    SemgrepSecurityProvider,
    TrivySecurityProvider,
    scrub_secrets,
)

from backend.release.events import (
    DecisionChangeEvent,
    DecisionLineageRecord,
    DecisionLineageTracker,
    DeterministicEntityResolver,
    EnterpriseEvent,
    EnterpriseEventType,
    EventIdempotencyManager,
    EventNormalizer,
    EventRouter,
    EvidenceGraph,
    EvidenceLifecycleManager,
    EvidenceLifecycleRecord,
    EvidenceState,
    GitHubEventNormalizer,
    GraphEdge,
    GraphEdgeType,
    GraphNode,
    GraphNodeType,
    ImpactAnalysisResult,
    IngestionReceipt,
    InvestigationImpactAnalyzer,
    JiraEventNormalizer,
    SecurityEventNormalizer,
    WebhookSecurityValidator,
)

# Brick 4.4 Durable Continuous Control Plane
from backend.release.persistence import (
    DatabaseMigrator,
    DurableStoreBundle,
    PersistenceFactory,
    SqliteConnectionPool,
)
from backend.release.workers import (
    AsyncWorkerEngine,
    TaskStatus,
    WorkerLeaseManager,
    WorkerTask,
)
from backend.release.drift import ContinuousDriftMonitor
from backend.release.replay import EventReplayEngine, ReplayReport
from backend.release.ingress import create_ingress_app
from backend.release.investigation import (
    recover_investigation_state,
    reconstruct_assessment_from_store,
    save_investigation_state,
)

# Brick 4.5 Live Enterprise Operations & Distributed Control Plane
from backend.release.connectivity.webhooks import (
    GitHubWebhookRegistrationProvider,
    InMemoryWebhookRegistrationProvider,
    JiraWebhookRegistrationProvider,
    WebhookDeliveryVerifier,
    WebhookRegistration,
    WebhookRegistrationProvider,
    WebhookRegistrationService,
    WebhookRegistrationStatus,
)
from backend.release.distributed import (
    DatabaseDistributedLockProvider,
    DistributedLockProvider,
    DistributedScheduler,
    DistributedWorkerCoordinator,
    InMemoryDistributedLockProvider,
    LockToken,
    NodeStatus,
    RedisDistributedLockProvider,
    ScheduledJobReport,
    WorkerNode,
)
from backend.release.observability import (
    GLOBAL_METRICS,
    GLOBAL_TRACER,
    MetricsRegistry,
    Span,
    SpanRecord,
    SpanStatus,
    TraceContext,
    Tracer,
)
from backend.release.connectivity.verification import (
    CapabilityStatus,
    PilotExecutionMode,
    ProviderVerificationHarness,
)
from backend.release.cli import OracleCLI
from backend.release.config import (
    DatabaseConfig,
    EnterpriseRuntimeConfig,
    IngressConfig,
    ObservabilityConfig,
    RedisConfig,
    SecurityConfig,
    TenancyConfig,
    WebhookConfig,
    WorkerConfig,
)
from backend.release.security import (
    EnvironmentSecretStore,
    InMemorySecretStore,
    KubernetesSecretStore,
    SecretStore,
    SupplyChainFinding,
    SupplyChainAuditReport,
    SupplyChainSecurityAuditor,
    mask_token,
    redact_sensitive_payload,
    SecurityIntelligenceAPI,
    SecurityInvestigationEngine,
    SecurityDecisionEngine as SecurityIntelligenceDecisionEngine,
    SecurityFindingNormalizer,
    DependencyIntelligenceEngine,
    ReachabilityIntelligenceEngine,
    ExploitabilityAssessmentEngine,
    CrossSystemSecurityCorrelator,
    SecurityContradictionEngine,
    RemediationIntelligenceEngine,
    SecurityPolicyEngine,
    SecurityVerificationEngine,
    SecurityAdvisoryExplainer,
    SecurityDecisionOutcome as SecurityIntelligenceDecisionOutcome,
    ReachabilityStatus,
    ExploitabilityLevel,
    SecurityInvestigation,
    AffectedDependency,
    ReachabilityAssessment,
    ExploitabilityAssessment,
    RemediationCandidate,
    SecurityContradictionRecord,
    SecurityVerification,
)
from backend.release.persistence.backup import (
    BackupMetadata,
    DatabaseBackupManager,
)
from backend.release.connectivity.tunnel import (
    CloudflareTunnelProvider,
    DeveloperTunnelProvider,
    MockTunnelProvider,
    NgrokTunnelProvider,
)

__all__ = [
    "ReleaseCandidate",
    "SecurityFinding",
    "SecurityCategory",
    "SecuritySeverity",
    "FindingStatus",
    "CIBuildStatus",
    "CIPipelineRun",
    "WorkItemStatus",
    "WorkItem",
    "CodeReviewStatus",
    "PullRequestReview",
    "ReleaseDecisionOutcome",
    "RiskLevel",
    "ReleaseRecommendation",
    "GovernedActionType",
    "GovernedActionStatus",
    "GovernedActionProposal",
    "ReleaseDecision",
    "ReleaseAssessment",
    "BaseReleaseDataProvider",
    "GitReleaseProvider",
    "WorkManagementProvider",
    "CICDProvider",
    "SecurityScanProvider",
    "InMemoryReleaseDataProvider",
    "CrossSystemCorrelator",
    "ReleaseReadinessInvestigator",
    "ReleaseDecisionEngine",
    "GovernedActionExecutor",
    "ReleaseReadinessAPI",
    "CircuitBreaker",
    "CircuitState",
    "CircuitBreakerOpenError",
    "ProviderNetworkError",
    "ProviderAuthenticationError",
    "ProviderRateLimitError",
    "ProviderTimeoutError",
    "ProviderOutageError",
    "ResilientHttpClient",
    "scrub_secrets",
    "CredentialProvider",
    "EnvCredentialProvider",
    "InMemoryCredentialVault",
    "SecretRedactor",
    "GLOBAL_REDACTOR",
    "GitHubReleaseProvider",
    "JiraWorkManagementProvider",
    "GitHubActionsCICDProvider",
    "SemgrepSecurityProvider",
    "TrivySecurityProvider",
    "EnterpriseReleaseDataProvider",
    # Brick 4.3 Event-Driven Intelligence & Evidence Graph
    "EnterpriseEvent",
    "EnterpriseEventType",
    "DecisionChangeEvent",
    "EventNormalizer",
    "GitHubEventNormalizer",
    "JiraEventNormalizer",
    "SecurityEventNormalizer",
    "WebhookSecurityValidator",
    "EventIdempotencyManager",
    "DeterministicEntityResolver",
    "InvestigationImpactAnalyzer",
    "ImpactAnalysisResult",
    "EvidenceState",
    "EvidenceLifecycleManager",
    "EvidenceLifecycleRecord",
    "EvidenceGraph",
    "GraphNode",
    "GraphNodeType",
    "GraphEdge",
    "GraphEdgeType",
    "DecisionLineageTracker",
    "DecisionLineageRecord",
    "EventRouter",
    "IngestionReceipt",
    # Brick 4.4 Durable Continuous Control Plane
    "DurableStoreBundle",
    "PersistenceFactory",
    "DatabaseMigrator",
    "SqliteConnectionPool",
    "WorkerLeaseManager",
    "AsyncWorkerEngine",
    "WorkerTask",
    "TaskStatus",
    "ContinuousDriftMonitor",
    "EventReplayEngine",
    "ReplayReport",
    "create_ingress_app",
    "save_investigation_state",
    "recover_investigation_state",
    "reconstruct_assessment_from_store",
    # Brick 4.5 Live Enterprise Operations & Distributed Control Plane
    "WebhookRegistration",
    "WebhookRegistrationStatus",
    "WebhookRegistrationProvider",
    "GitHubWebhookRegistrationProvider",
    "JiraWebhookRegistrationProvider",
    "InMemoryWebhookRegistrationProvider",
    "WebhookDeliveryVerifier",
    "WebhookRegistrationService",
    "DistributedLockProvider",
    "LockToken",
    "InMemoryDistributedLockProvider",
    "DatabaseDistributedLockProvider",
    "RedisDistributedLockProvider",
    "DistributedWorkerCoordinator",
    "WorkerNode",
    "NodeStatus",
    "GLOBAL_METRICS",
    "MetricsRegistry",
    "CapabilityStatus",
    "PilotExecutionMode",
    "ProviderVerificationHarness",
    "OracleCLI",
    # Brick 4.6 Deployable Enterprise Runtime & Observability
    "EnterpriseRuntimeConfig",
    "DatabaseConfig",
    "RedisConfig",
    "WebhookConfig",
    "WorkerConfig",
    "SecurityConfig",
    "ObservabilityConfig",
    "IngressConfig",
    "TenancyConfig",
    "SecretStore",
    "EnvironmentSecretStore",
    "KubernetesSecretStore",
    "InMemorySecretStore",
    "mask_token",
    "redact_sensitive_payload",
    "GLOBAL_TRACER",
    "Tracer",
    "Span",
    "SpanRecord",
    "SpanStatus",
    "TraceContext",
    "DistributedScheduler",
    "ScheduledJobReport",
    "DatabaseBackupManager",
    "BackupMetadata",
    "DeveloperTunnelProvider",
    "MockTunnelProvider",
    "CloudflareTunnelProvider",
    "NgrokTunnelProvider",
    "SupplyChainSecurityAuditor",
    "SupplyChainAuditReport",
    # Brick 4.7 Security Intelligence Engine
    "SecurityIntelligenceAPI",
    "SecurityInvestigationEngine",
    "SecurityIntelligenceDecisionEngine",
    "SecurityFindingNormalizer",
    "DependencyIntelligenceEngine",
    "ReachabilityIntelligenceEngine",
    "ExploitabilityAssessmentEngine",
    "CrossSystemSecurityCorrelator",
    "SecurityContradictionEngine",
    "RemediationIntelligenceEngine",
    "SecurityPolicyEngine",
    "SecurityVerificationEngine",
    "SecurityAdvisoryExplainer",
    "SecurityIntelligenceDecisionOutcome",
    "ReachabilityStatus",
    "ExploitabilityLevel",
    "SecurityInvestigation",
    "AffectedDependency",
    "ReachabilityAssessment",
    "ExploitabilityAssessment",
    "RemediationCandidate",
    "SecurityContradictionRecord",
    "SecurityVerification",
]

