{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "oracle.fullname" . }}-role
  labels:
    {{- include "oracle.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "oracle.fullname" . }}-rb
  labels:
    {{- include "oracle.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "oracle.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "oracle.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
