{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle.fullname" . }}-secrets
  labels:
    {{- include "oracle.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: "change_me_in_production"
  redis-password: "change_me_in_production"
  webhook-secret: "change_me_in_production_hex"
{{- end }}
